import type { IntegratedDocument } from './types';

export const mockDocuments: IntegratedDocument[] = [
  {
    id: 'doc-001',
    documentName: '김민수 활동지원급여 제공계획서',
    documentType: '급여제공계획서',
    clientName: '김민수',
    assistantName: '박지원',
    baseMonth: '2026-05',
    registeredAt: '2026-05-03',
    registeredBy: '황정희',
    status: '정상',
    fileName: 'kim_minsu_care_plan_2026_05.pdf',
    fileType: 'PDF',
    fileSize: '1.2MB',
    targetType: '이용자',
  },
  {
    id: 'doc-002',
    documentName: '이영희 이용내역서',
    documentType: '이용내역서',
    clientName: '이영희',
    assistantName: '최도움',
    baseMonth: '2026-05',
    registeredAt: '2026-05-05',
    registeredBy: '백해준',
    status: '검토 필요',
    fileName: 'usage_lee_younghee_2026_05.xlsx',
    fileType: 'XLSX',
    fileSize: '842KB',
    targetType: '이용자',
  },
  {
    id: 'doc-003',
    documentName: '박지원 근로계약서',
    documentType: '계약서',
    clientName: '-',
    assistantName: '박지원',
    baseMonth: '2026-04',
    registeredAt: '2026-04-21',
    registeredBy: '이윤석',
    status: '정상',
    fileName: 'assistant_contract_park_jiwon.pdf',
    fileType: 'PDF',
    fileSize: '980KB',
    targetType: '활동지원사',
  },
  {
    id: 'doc-004',
    documentName: '정하늘 개인정보 수집 이용 동의서',
    documentType: '개인정보동의서',
    clientName: '정하늘',
    assistantName: '한보람',
    baseMonth: '2026-03',
    registeredAt: '2026-03-30',
    registeredBy: '황정희',
    status: '만료 예정',
    fileName: 'privacy_agreement_jung_haneul.pdf',
    fileType: 'PDF',
    fileSize: '620KB',
    targetType: '이용자',
  },
  {
    id: 'doc-005',
    documentName: '최도움 제공기록지',
    documentType: '제공기록지',
    clientName: '오세민',
    assistantName: '최도움',
    baseMonth: '2026-05',
    registeredAt: '2026-05-08',
    registeredBy: '이윤석',
    status: '누락',
    fileName: '-',
    fileType: '-',
    fileSize: '-',
    targetType: '이용자',
  },
  {
    id: 'doc-006',
    documentName: '한보람 활동지원사 교육 이수증',
    documentType: '기타',
    clientName: '-',
    assistantName: '한보람',
    baseMonth: '2026-02',
    registeredAt: '2026-02-14',
    registeredBy: '백해준',
    status: '정상',
    fileName: 'certificate_han_boram.jpg',
    fileType: 'JPG',
    fileSize: '2.4MB',
    targetType: '활동지원사',
  },
  {
    id: 'doc-007',
    documentName: '오세민 이용내역서',
    documentType: '이용내역서',
    clientName: '오세민',
    assistantName: '박지원',
    baseMonth: '2026-04',
    registeredAt: '2026-04-28',
    registeredBy: '황정희',
    status: '검토 필요',
    fileName: 'usage_oh_semin_2026_04.pdf',
    fileType: 'PDF',
    fileSize: '1.8MB',
    targetType: '이용자',
  },
  {
    id: 'doc-008',
    documentName: '최도움 건강 관련 확인서',
    documentType: '기타',
    clientName: '-',
    assistantName: '최도움',
    baseMonth: '2026-05',
    registeredAt: '2026-05-07',
    registeredBy: '이윤석',
    status: '만료 예정',
    fileName: 'health_check_choi_doum.pdf',
    fileType: 'PDF',
    fileSize: '760KB',
    targetType: '활동지원사',
  },
  {
    id: 'doc-009',
    documentName: '김민수 계약서',
    documentType: '계약서',
    clientName: '김민수',
    assistantName: '박지원',
    baseMonth: '2026-01',
    registeredAt: '2026-01-11',
    registeredBy: '백해준',
    status: '정상',
    fileName: 'client_contract_kim_minsu.pdf',
    fileType: 'PDF',
    fileSize: '1.1MB',
    targetType: '이용자',
  },
  {
    id: 'doc-010',
    documentName: '이영희 제공기록지',
    documentType: '제공기록지',
    clientName: '이영희',
    assistantName: '최도움',
    baseMonth: '2026-03',
    registeredAt: '2026-03-18',
    registeredBy: '황정희',
    status: '누락',
    fileName: '-',
    fileType: '-',
    fileSize: '-',
    targetType: '이용자',
  },
];